### ISSUE TITLE
Feature Request: Resize Source Image

### ISSUE THREAD

**Issue by atomdmac** [reonZ/easy-token#1]
It would be incredibly useful if it were possible to resize the source images inside of the Easy Token window.  I often have images that are slightly too large/small for the circular border.

**Comment by reonZ** [comment]
sadly this goes beyond my skills, i don't know anything about implementing graphical tools, also, i haven't touch this module since i made it more than a year ago and don't even use it anymore (we now have a huge token pack in the pf2e system so, there is not really a need for this anymore)
